--- #YAML:1.0
name:                Hook-Filter
version:             0.08
abstract:            A runtime firewall for subroutine calls
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    File::Spec:                    0.86
    Module::Pluggable:             2.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Erwan Lemonnier <erwan@cpan.org>
