# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Hook-Filter
version:      0.02
version_from: lib/Hook/Filter.pm
installdirs:  site
requires:
    File::Spec:                    0.86
    Module::Pluggable:             2.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
